# Generated by Django 4.0.2 on 2022-03-21 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(null=True)),
                ('trailer', models.TextField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('release_date', models.CharField(max_length=10)),
                ('rating', models.FloatField(null=True)),
                ('votes', models.FloatField(null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('geners', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.genres')),
            ],
        ),
    ]
