# Generated by Django 4.0.2 on 2022-03-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movie_geners_movie_geners_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='geners',
            field=models.ManyToManyField(blank=True, to='movie.Genre'),
        ),
    ]
